### ISSUE TITLE
Hot reloading users/reviewers list

### ISSUE THREAD

**Issue by aurimasrazmis** [AngelVI13/slack-assistant#8]
Currently we need to delete reviewers temporary list and restart the bot in order to add new reviewer.
Suggestion: take new users/reviewers data from users file after temporary list gets reset (gets empty).

**Comment by aurimasrazmis** [comment]
Suggestion: would be convenient to have restarting picker bot command. 
It would help to have refreshed reviewers list before new sprint

**Comment by AngelVI13** [comment]
Partial hot reloading (reset of reviewers) is added here #10

**Comment by AngelVI13** [comment]
Full fix + users update here, #12
